# This is a basic workflow to help you get started with Actions

name: Builds and pushes Edaga to github deploy

on:
  push:
    branches: [ main ]
permissions:
  contents: write

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
